# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

s1 = Screenshot.create(isFinished: false, assignee: "Jaemin", image: "https://user-images.githubusercontent.com/17509651/43684963-14b98a6c-98e5-11e8-8a31-91b1554d34bd.png")


t1 = Type.create(name: 'Text', color: 'bg-0')
t2 = Type.create(name: 'Image', color: 'bg-1')
t3 = Type.create(name: 'Graph', color: 'bg-2')
t4 = Type.create(name: 'Ad', color: 'bg-3')
t5 = Type.create(name: 'Uncertain', color: 'bg-4')

u1 = Piece.create(screenshot_id: s1.id, type_id: t1.id, left: 30, top: 20, width: 65, height: 40) # image

Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/0.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/1.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/2.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/3.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/4.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/5.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/6.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/7.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/8.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/9.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/10.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/11.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/12.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/13.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/14.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/15.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/16.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/17.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/18.png")
Screenshot.create(isFinished: false, assignee: "Kiroong", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/19.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/20.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/21.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/22.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/23.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/24.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/25.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/26.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/27.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/28.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/29.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/30.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/31.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/32.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/33.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/34.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/35.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/36.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/37.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/38.png")
Screenshot.create(isFinished: false, assignee: "Jaeyoon", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/39.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/40.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/41.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/42.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/43.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/44.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/45.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/46.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/47.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/48.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/49.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/50.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/51.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/52.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/53.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/54.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/55.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/56.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/57.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/58.png")
Screenshot.create(isFinished: false, assignee: "Jaemin", image:"https://github.com/CHIroong/V2A/raw/master/crawler/screenshot/59.png")



